services:
  - type: web
    name: django-chat
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT chat_project.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: django-chat-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: django-chat-redis
          type: redis
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        value: "us-east-1"

  - type: redis
    name: django-chat-redis
    ipAllowList: []
    plan: free

databases:
  - name: django-chat-db
    databaseName: django_chat
    plan: free
