services:
  - type: web
    name: chat-app
    env: python
    buildCommand: ./build.sh
    startCommand: daphne chat_project.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SETTINGS_MODULE
        value: chat_project.production_settings
      - key: DATABASE_URL
        fromDatabase:
          name: chat-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chat-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1

  - type: redis
    name: chat-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: volatile-lru
    maxmemoryMb: 25

databases:
  - name: chat-db
    databaseName: chatdb
    plan: free
    ipAllowList: []
